definitions:
  main.helloResponse:
    properties:
      response:
        example: hello user
        type: string
    type: object
  main.httpError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is gin server with rk-boot.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /v1/hello:
    get:
      consumes:
      - application/json
      description: Say hello to incoming name.
      operationId: v1.api.hello
      parameters:
      - description: Your name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            request-id:
              description: Request id for with uuid generator.
              type: string
          schema:
            $ref: '#/definitions/main.helloResponse'
        "400":
          description: Bad Request
          headers:
            request-id:
              description: Request id for with uuid generator.
              type: string
          schema:
            $ref: '#/definitions/main.httpError'
      summary: Hello
      tags:
      - Hello
schemes:
- http
- https
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
